### ISSUE TITLE
AssertionError [ERR_ASSERTION]: protocol mismatch

### ISSUE THREAD

**Issue by juree** [mowlc/real-estate-scraper#4]
Hello,
i came across with this problem:

```
Tue Jan 09 2018 13:55:51 GMT+0000 (UTC) STARTED
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: protocol mismatch
    at parseOptions (/home/ubuntu/real-estate-scraper/node_modules/follow-redirects/create.js:131:10)
    at H.request (/home/ubuntu/real-estate-scraper/node_modules/follow-redirects/create.js:108:19)
    at tinyreq (/home/ubuntu/real-estate-scraper/node_modules/tinyreq/lib/index.js:73:65)
    at Timeout._onTimeout (/home/ubuntu/real-estate-scraper/scraper.js:131:5)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

Client ID and clientSecret were obtained from Google dev console. My first guess what can cause this error is some incompatible version of some library or node itself?
I tried to run run this on Node v8.9.4.

Any help is appreciated.

**Comment by mowlc** [comment]
Hi,
I don't think the problem is with mailing service. According to trace, I would say the problem occurs while making the request - in tinyreq library. It's possible that libraries are not compatible with your version of node. I'm running 9.6.0. Try upgrading node and then report back and I'll try to help you.

**Comment by juree** [comment]
Hm, i updated my node to last version v9.4.0 but problem remains. 

Version of other libraries:
tinyreq@3.3.1
nodemailer@4.4.2
node-json-db@0.7.3
cheerio@1.0.0-rc.2

What else can it be?
